# PANDAS

Libreria molto popolare nel linguaggio di <b>programmazione Python</b> utilizzata per l'analisi dei dati e la <b>manipolazione di dati tabulari</b>.

<b>Strutture dati principali</b>:
 - <b>DataFrame</b>: Una struttura <b>dati tabellare</b> bidimensionale <b>simile a un foglio di calcolo</b>, composta da righe e colonne. È usato per rappresentare e manipolare dati in formato tabellare.
 - <b>Series</b>: Una struttura dati <b>unidimensionale</b> che rappresenta una singola colonna o una riga di un DataFrame. È simile a un array o una lista, ma con etichette (indice) per ciascun elemento.
 
<b>Import/Export</b>: Pandas offre funzioni per leggere dati da una varietà di formati, inclusi CSV, Excel, SQL, JSON e altro. Puoi anche esportare dati in questi formati.

<b>Manipolazione dei dati</b>: Pandas offre numerose funzioni per la pulizia e la manipolazione dei dati, tra cui la <b>rimozione di duplicati, la gestione dei valori mancanti, la concatenazione, l'aggregazione, il raggruppamento, la trasposizione e altro</b>.

In [3]:
pip install pandas

In [4]:
pip install pip openpyxl

#

### Lettura file excel

In [19]:
import pandas as pd

coding     = pd.read_excel("File/CSV/liste coding e non-coding RNA.xlsx", sheet_name="posizioni coding RNA")
non_coding = pd.read_excel("File/CSV/liste coding e non-coding RNA.xlsx", sheet_name="posizioni non-coding RNA")

In [20]:
coding.head(10)  # --> ritorna i primi 10 elementi presenti nel dataframe

          name  chrom strand    txStart      txEnd   name2
0  NM_000014.5  chr12      -    9067707    9116229     A2M
1  NM_000015.2   chr8      +   18391244   18401213    NAT2
2  NM_000016.5   chr1      +   75724346   75763679   ACADM
3  NM_000017.3  chr12      +  120725737  120740008   ACADS
4  NM_000018.3  chr17      +    7219830    7225267  ACADVL
5  NM_000019.3  chr11      +  108121530  108148168   ACAT1
6  NM_000020.2  chr12      +   51907417   51923361  ACVRL1
7  NM_000021.3  chr14      +   73136434   73223691   PSEN1
8  NM_000022.3  chr20      -   44619518   44651758     ADA
9  NM_000023.3  chr17      +   50165984   50175932    SGCA

In [21]:
non_coding.head(10)

          name  chrom strand    txStart      txEnd     name2
0  NR_000005.1  chr11      +   75400390   75400538  SNORD15A
1  NR_000006.8   chr1      +   92837288   92837383   SNORD21
2  NR_000007.1   chr4      +  151103826  151103891  SNORD73A
3  NR_000008.2  chr11      -   62852909   62853035   SNORD22
4  NR_000009.1  chr17      +   28723680   28723754   SNORD4B
5  NR_000010.1  chr17      +   28722581   28722653   SNORD4A
6  NR_000011.1   chrX      +  154400280  154400415   SNORA70
7  NR_000012.1  chr19      +   17862587   17862720   SNORA68
8  NR_000013.1  chr17      +   28720549   28720616  SNORD42B
9  NR_000014.1  chr17      +   28723429   28723491  SNORD42A

#### Eliminazione colonna name in entrambi i DataFrame

In [22]:
coding.drop(columns="name", inplace=True)
non_coding.drop(columns="name", inplace=True)

#### Rinominare name2 in Coding (dataframe coding) e NonCoding (dataframe non_coding)

In [23]:
coding.rename(columns={"name2": "coding"}, inplace=True)
non_coding.rename(columns={"name2": "non_coding"}, inplace=True)

#### primi 10000 campioni

In [24]:
coding = coding[:10000]
non_coding = non_coding[:10000]

#### Join tra due DataFrame
merge(right, how='inner', on=None, left_on=None, right_on=None, ...)
 - how: {‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’}, default ‘inner’
 - on: nome della colonna (in entrambi i df) che deve essere utilizzata per la join.
 - left_on, right_on: sono usati in sostituzione a on se le colonne nei due df hanno nomi differenti.

In [25]:
coding_no_coding = pd.merge(coding, non_coding, on="chrom")

In [26]:
coding_no_coding

,chrom,strand_x,txStart_x,txEnd_x,coding,strand_y,txStart_y,txEnd_y,non_coding
0,chr12,-,9067707,9116229,A2M,-,56645026,56645101,SNORD59A
1,chr12,-,9067707,9116229,A2M,+,13000441,13004830,HTR7P1
2,chr12,-,9067707,9116229,A2M,+,6883980,6884614,RPL13P5
3,chr12,-,9067707,9116229,A2M,-,121795266,121802946,LINC01089
4,chr12,-,9067707,9116229,A2M,+,9648046,9658415,LOC374443
...,...,...,...,...,...,...,...,...,...
4947747,chrY,-,1403138,1452977,ASMTL,+,22316677,22320384,LOC100652931
4947748,chrY,-,1403138,1452977,ASMTL,+,2609190,2609254,MIR6089
4947749,chrY,-,1403138,1452977,ASMTL,+,22438939,22484714,LOC101929148
4947750,chrY,-,1403138,1452977,ASMTL,-,57212177,57214703,DDX11L16
4947751,chrY,-,1403138,1452977,ASMTL,-,1190495,1212723,CRLF2

#### Comprensione del filtraggio
 - garantiamo che stand_x e stand_y siano di segno opposto

In [27]:
condizione = coding_no_coding["strand_x"] != coding_no_coding["strand_y"]
coding_no_coding[condizione]

,chrom,strand_x,txStart_x,txEnd_x,coding,strand_y,txStart_y,txEnd_y,non_coding
1,chr12,-,9067707,9116229,A2M,+,13000441,13004830,HTR7P1
2,chr12,-,9067707,9116229,A2M,+,6883980,6884614,RPL13P5
4,chr12,-,9067707,9116229,A2M,+,9648046,9658415,LOC374443
8,chr12,-,9067707,9116229,A2M,+,132031223,132031360,SNORA49
11,chr12,-,9067707,9116229,A2M,+,98599634,98599884,SNORA53
...,...,...,...,...,...,...,...,...,...
4947691,chrY,-,1403138,1452977,ASMTL,+,14523504,14843968,NLGN4Y
4947692,chrY,-,1403138,1452977,ASMTL,+,3002995,3102272,LINC00278
4947747,chrY,-,1403138,1452977,ASMTL,+,22316677,22320384,LOC100652931
4947748,chrY,-,1403138,1452977,ASMTL,+,2609190,2609254,MIR6089
4947749,chrY,-,1403138,1452977,ASMTL,+,22438939,22484714,LOC101929148

#### Utilizzo funzione apply

<b>NOTA</b>:
     
     + indica txStart_x ----------> txEnd_x
     - indica txStart_y <----------	txEnd_y

Vogliamo tenere tutte le righe della tabella tale che + e - siano totalmente o parzialmente sovrapposti

<b>Esempio</b>:
     
     + indica  ----------> 
     - indica       <----------

In [32]:
def sovrapposizione(row):
    if row["txStart_y"] < row["txEnd_x"] <= row["txEnd_y"]:
        return row["txEnd_x"] - row["txStart_y"]
    if row["txStart_x"] < row["txEnd_y"] <= row["txEnd_x"]:
        return row["txEnd_y"] - row["txStart_x"]
    return -1

coding_no_coding["sovrapposizione"] = coding_no_coding.apply(lambda x: sovrapposizione(x), axis=1)

In [34]:
# loc -> selezionare righe e colonne in un DataFrame utilizzando etichette o etichette booleane.
coding_no_coding = coding_no_coding.loc[coding_no_coding["sovrapposizione"] >= 0]

In [35]:
coding_no_coding

,chrom,strand_x,txStart_x,txEnd_x,coding,strand_y,txStart_y,txEnd_y,non_coding,sovrapposizione
58,chr12,-,9067707,9116229,A2M,+,9065176,9068055,A2M-AS1,348
1735,chr12,-,57747726,57752447,CDK4,-,57748617,57748682,MIR6759,956
2055,chr12,-,114353929,114408442,TBX5,+,114408194,114412832,TBX5-AS1,248
3016,chr12,+,52949058,52952901,KRT18,-,52897186,52949866,KRT8,808
4504,chr12,+,48119229,48146404,PFKM,+,48132796,48132867,MIR6505,13638
...,...,...,...,...,...,...,...,...,...,...
4946760,chrY,+,14622020,14733549,NLGN4Y,+,14523504,14843968,NLGN4Y,210045
4947536,chrY,-,1403138,1453762,ASMTL,+,1400530,1413586,ASMTL-AS1,10448
4947537,chrY,-,1403138,1453762,ASMTL,+,1400530,1415421,ASMTL-AS1,12283
4947669,chrY,-,1403138,1452977,ASMTL,+,1400530,1413586,ASMTL-AS1,10448
4947670,chrY,-,1403138,1452977,ASMTL,+,1400530,1415421,ASMTL-AS1,12283

#### Selezioniamo un sott'insieme di colonne (teniamo solo chrom, coding, non_coding, sovrapposizione)

In [44]:
coding_no_coding = coding_no_coding[["chrom", "coding", "non_coding", "sovrapposizione"]].reset_index(drop=True)

In [45]:
coding_no_coding

      chrom  coding non_coding  sovrapposizione
0     chr12     A2M    A2M-AS1              348
1     chr12    CDK4    MIR6759              956
2     chr12    TBX5   TBX5-AS1              248
3     chr12   KRT18       KRT8              808
4     chr12    PFKM    MIR6505            13638
...     ...     ...        ...              ...
4003   chrY  NLGN4Y     NLGN4Y           210045
4004   chrY   ASMTL  ASMTL-AS1            10448
4005   chrY   ASMTL  ASMTL-AS1            12283
4006   chrY   ASMTL  ASMTL-AS1            10448
4007   chrY   ASMTL  ASMTL-AS1            12283

[4008 rows x 4 columns]

#### Group by

In [51]:
coding_no_coding.groupby(
    by=["chrom", "coding", "non_coding"]
).agg({'sovrapposizione': ['mean', 'min', 'max']})

                         sovrapposizione
                                    mean     min     max
chrom coding  non_coding
chr1  AADACL3 AADACL3       12645.000000   12645   12645
      ALDH4A1 MIR4695       11846.000000   11846   11846
      APH1A   APH1A          3811.000000    3811    3811
      ARF1    MIR3620       14355.333333   14192   14682
      ARHGEF2 MIR6738        4498.000000    4498    4498
...                                  ...     ...     ...
chrY  CSF2RA  MIR3690       21723.500000   11315   25193
      HSFY2   HSFY2         42276.000000   42276   42276
              TTTY9A         7758.000000    7758    7758
      NLGN4Y  NLGN4Y       209510.500000  208976  210045
      VAMP7   VAMP7         62490.000000   62490   62490

[1723 rows x 3 columns]